### PR TITLE
	[FIX] for Fatal error: Call to a member function lang()

### PR DESCRIPTION
**Pull request by Galixte**
Hi @oxpus,

i’m sorry i found an other problems, but i found also the solution :)

### CODE REVIEW

**Comment by Galixte** [comment]
It’s strange on 3.2 version, phpBB 3.2.x doesn’t report to me any error message while the line https://github.com/oxpus/Basis-Statistics-32/blob/master/oxpus/basicstats/controller/main.php#L618 has ```('COLON')``` instead of here where it’s ```$this->language->lang['COLON']```.

You know why ?

**Comment by Galixte** [comment]
It’s my answer ? https://github.com/oxpus/Basis-Statistics-32/pull/4

**Comment by oxpus** [comment]
The fix is only needed for the phpBB 3.1 extension.
Since phpBB 3.2 the object $language is oblicatory, $user->lang on the other hand is deprecated.

**Comment by Galixte** [comment]
Thanks!

**Pull request merged**
